Reintroduce #257
boostorg/fusion pull request #261
Opened 2022-10-10 02:35 UTC by Kojoley

2022-10-10 02:42 UTC, djowel commented
@denzor200 I'm going to merge this after checks have completed. But please comment if you will.

2022-10-10 05:20 UTC, denzor200 requested changes

2022-10-10 05:20 UTC, denzor200 commented on include/boost/fusion/view/transform_view/detail/deref_data_impl.hpp
> +#include <boost/type_traits/add_const.hpp>
redundantly changes in deref_data_impl.hpp

2022-10-11 02:28 UTC, merged

2022-10-18 18:12 UTC, Kojoley commented
@djowel could you please merge develop to master to include this in the next release?

2022-10-18 21:28 UTC, djowel commented
Merged.